### PR TITLE
Issue: When version/locale/component format is incorrect, the response message is not kindly

### LINKED ISSUE #1104: [BUG] [Go service] When version/locale/component  format is incorrect, the response message is not kindly
**Describe the bug**
When version/locale/component  format is incorrect, the response message is not kindly  of below APIs :
translation-product-component-api
translation-product-component-key-api

**To Reproduce**
productName=VMwareVIP;component=big custom@！;version=1.1.0;locale=zh_CN;

**Expected behavior**
code=400;
message=Incorrect component(only allows letter, number, dot, underline, dashline)

**Screenshots**
image
image
image

**Desktop (please complete the following information):**
 - Browser Name [ chrome]
 - Browser Version [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by Xiaochao8**

### CODE REVIEW

File: api/utils.go [hunk 1]
```diff
@@ -82,7 +100,7 @@ func ToBusinessError(err error) *BusinessError {
 			}
 			return &BusinessError{Code: sgtnerror.UnknownError.Code(), HTTPCode: sgtnerror.UnknownError.HTTPCode(), UserMsg: e.Error()}
```
Comment (tigershi) [inline api/utils.go:101]: why this error can't define in types.go file

Comment (Xiaochao8) [reply api/utils.go:101]: The user error message is special for each error. 
UserMsg: e.Error()}

**Review by tigershi — APPROVED** [review]

**Review by linr211 — APPROVED** [review]
